name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add any additional steps specific to the main workflow here

      - name: Config for Actions
      # You may pin to the exact commit or the version.
      # uses: Monorepo-Actions/config-for-actions@47b0824054f9eef4a5d1b2df11f4c76b9b0d9117
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          # The configuration files.
          config_files: .github/workflows/test.yml
