name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps for the test workflow here
      - name: run a test command
        run: echo "calling from test.yml"
